### ISSUE TITLE
Wanted to share customized dashboard setup example

### ISSUE THREAD

**Issue by ahuffman** [sh00t2kill/dolphin-robot#156]
Hi @sh00t2kill , wanted to share for others my dashboard setup making use of the `custom:vacuum-card` front-end integration you mentioned in documentation from HACS.  Feel free to add into your documentation as an example.

Cleaning Mode view:
![image](https://github.com/sh00t2kill/dolphin-robot/assets/4340269/861907cd-b8f5-4c9e-8944-7a932876fd7a)

Inactive/Off view:
![image](https://github.com/sh00t2kill/dolphin-robot/assets/4340269/9b461654-def7-4cc7-a078-fc722e054225)

The one thing I wish I could change is the fan display in top left corner, and the buttons (no need for dock button), but not exposed in the card config as an option.

Here's the code I put together for this:

```yaml
type: custom:vacuum-card
entity: vacuum.huffbot
stats:
  default:
    - entity_id: sensor.huffbot_cycle_count
      subtitle: Cycles Completed
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_status
      subtitle: Status
      value_template: |
        {% if value == "init" %}Initializing{% endif %}
        {% if value == "off" %}Off{% endif %}
        {% if value == "cleaning" %}Cleaning{% endif %}
  cleaning:
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_cycle_time
      subtitle: Cycle
      value_template: '{{ value | float(0) / 60 }}'
      unit: Hour
    - entity_id: sensor.huffbot_cycle_time_left
      subtitle: Remaining
      value_template: '{{ ( value | float(0) / 60) | round }}'
      unit: Minutes
    - entity_id: select.huffbot_led_mode
      subtitle: LED Mode
      value_template: |
        {% if value == "1" %}Blinking{% endif %}
        {% if value == "2" %}Always On{% endif %}
        {% if value == "3" %}Disco{% endif %}
    - entity_id: number.huffbot_led_intensity
      subtitle: LED Intensity
      unit: '%'
image: /local/robot_icon_c.svg
show_status: false
show_name: true
```
